import { EventItem } from "@/types";

export const INITIAL_EVENTS: EventItem[] = [
  /* CONCERTS & MUSIC (5 IMAGES) */
  {
    id: "evt-1",
    title: "Sol Generation: The Sun & Stars Festival 2026",
    tagline: "Experience the magic of East African live rhythms under the stars",
    category: "Concerts",
    date: "2026-12-19",
    time: "18:00 PM",
    venue: "Ngong Racecourse, Nairobi",
    city: "Nairobi",
    priceFrom: 2500,
    bannerImage: "/Concert1.jpeg",
    description:
      "Bringing together the biggest stars in East Africa for an unforgettable night of rhythm, culture, and celebration. The Sun & Stars Festival is a movement celebrating our roots while looking towards a bright, creative future. Expect world-class production, immersive art installations, and a curated food court featuring the finest Nairobi street food.",
    tags: ["#NairobiEvents", "#SolGeneration", "#AfricanMusic", "#LiveConcert"],
    isPassed: false,
    isFeatured: true,
    ticketTiers: [
      {
        id: "tier-1-1",
        name: "Early Bird Pass",
        price: 2500,
        description: "General Admission access with early bird perk",
        availableQuantity: 45,
        earlyBirdEnabled: true,
      },
      {
        id: "tier-1-2",
        name: "Regular Gate Access",
        price: 3500,
        description: "Gate entry & main concert floor access",
        availableQuantity: 320,
      },
      {
        id: "tier-1-3",
        name: "VIP Deck Experience",
        price: 8000,
        description: "Premium elevated deck, express bar & welcome drinks",
        availableQuantity: 80,
        isPopular: true,
      },
    ],
    vendorOpening: {
      id: "v-1",
      category: "Food & Beverage",
      title: "Gourmet Street Food & Craft Cocktails Vendor Slot",
      spotsNeeded: 12,
      spotsRemaining: 4,
      boothFee: 15000,
      boothSize: "3m x 3m Canopy Space",
      perks: ["220V Power Outlet Provided", "4 Vendor Passes Included", "Featured in Event Map"],
      deadline: "2026-11-30",
    },
  },
  {
    id: "evt-2",
    title: "Afro-House Sunset Session: Vibes on the Deck",
    tagline: "Deep afro house grooves, sunset cocktails & rooftop energy",
    category: "Concerts",
    date: "2026-10-05",
    time: "16:00 PM",
    venue: "Alchemist Bar, Westlands",
    city: "Nairobi",
    priceFrom: 1500,
    bannerImage: "/Concert2.jpeg",
    description:
      "An electric rooftop sunset session featuring international DJs, acoustic percussionists, signature mixology, and vibrant light shows over the Westlands skyline.",
    tags: ["#AfroHouse", "#SunsetSession", "#NairobiNightlife", "#DeepHouse"],
    isPassed: false,
    isFeatured: true,
    ticketTiers: [
      {
        id: "tier-2-1",
        name: "Standard Entry",
        price: 1500,
        description: "Access to main deck dancefloor",
        availableQuantity: 90,
      },
      {
        id: "tier-2-2",
        name: "VIP Lounge Table",
        price: 10000,
        description: "Reserved couch for 4 + premium bottle service",
        availableQuantity: 8,
        isPopular: true,
      },
    ],
  },
  {
    id: "evt-3",
    title: "East African Jazz & Soul Jam 2026",
    tagline: "Smooth saxophone solos, jazz improvisation & candlelit tables",
    category: "Concerts",
    date: "2026-11-08",
    time: "19:30 PM",
    venue: "Carnivore Grounds, Langata",
    city: "Nairobi",
    priceFrom: 3000,
    bannerImage: "/Concert3.jpeg",
    description:
      "A soulful night showcasing legendary East African jazz brass ensembles, soul vocalists, and fusion bands performing under ambient lighting.",
    tags: ["#LiveJazz", "#NairobiMusic", "#SoulJam", "#JazzFest"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-3-1",
        name: "General Seating",
        price: 3000,
        description: "Reserved table seating with complimentary welcome drink",
        availableQuantity: 150,
      },
    ],
  },
  {
    id: "evt-4",
    title: "Mombasa Reggae & Beach Bass Carnival",
    tagline: "Roots reggae riddims, dub sound systems & ocean breeze",
    category: "Concerts",
    date: "2026-12-28",
    time: "15:00 PM",
    venue: "Bamburi Beach Amphitheatre, Mombasa",
    city: "Mombasa",
    priceFrom: 2000,
    bannerImage: "/Concert4.jpeg",
    description:
      "Feel the vibration on the sandy shores of Mombasa. Live reggae bands, sound system battles, Swahili beach bites, and bonfire jams till sunrise.",
    tags: ["#CoastReggae", "#MombasaVibes", "#BeachConcert"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-4-1",
        name: "Beach Pass",
        price: 2000,
        description: "Access to main beach stage & bonfire area",
        availableQuantity: 200,
      },
    ],
  },
  {
    id: "evt-5",
    title: "Acoustic Unplugged: Intimate Sessions",
    tagline: "Stripped-back acoustic melodies & storyteller songcraft",
    category: "Concerts",
    date: "2026-10-24",
    time: "18:30 PM",
    venue: "KICC Courtyard, City Centre",
    city: "Nairobi",
    priceFrom: 1800,
    bannerImage: "/Concert5.jpeg",
    description:
      "An intimate acoustic gathering featuring singer-songwriters, guitarists, and storytellers sharing original compositions and stripped-down hits.",
    tags: ["#AcousticLive", "#Songwriters", "#Unplugged"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-5-1",
        name: "Audience Ticket",
        price: 1800,
        description: "Open seating access",
        availableQuantity: 110,
      },
    ],
  },

  /* TECH & INNOVATION (5 IMAGES) */
  {
    id: "evt-6",
    title: "Safari Tech Summit 2026",
    tagline: "Building the Next Era of AI, Fintech & Web Architecture in Africa",
    category: "Tech",
    date: "2026-11-12",
    time: "08:30 AM",
    venue: "Sarit Expo Centre, Westlands",
    city: "Nairobi",
    priceFrom: 4500,
    bannerImage: "/Tech1.jpeg",
    description:
      "Join over 1,500 software engineers, founders, VC investors, and digital innovators for keynotes, live coding workshops, hackathons, and product launches shaping Africa's technological ecosystem.",
    tags: ["#TechSummit", "#AI", "#DevCon", "#NairobiTech"],
    isPassed: false,
    isFeatured: true,
    ticketTiers: [
      {
        id: "tier-6-1",
        name: "Developer Pass",
        price: 4500,
        description: "Access to all technical tracks, demo hall & lunch",
        availableQuantity: 150,
      },
      {
        id: "tier-6-2",
        name: "VIP Founder & Executive Pass",
        price: 12000,
        description: "Investor lounge access, VIP networking dinner & keynote seating",
        availableQuantity: 30,
        isPopular: true,
      },
    ],
    vendorOpening: {
      id: "v-2",
      category: "Tech Demos",
      title: "Hardware & SaaS Interactive Exhibition Booths",
      spotsNeeded: 8,
      spotsRemaining: 2,
      boothFee: 25000,
      boothSize: "4m x 3m Modular Shell Scheme",
      perks: ["Gigabit Wi-Fi", "Dual 4K TV Mounts", "Mainstage Demo Slot (10 min)"],
      deadline: "2026-10-25",
    },
  },
  {
    id: "evt-7",
    title: "Silicon Savannah AI & Cloud Hackathon",
    tagline: "48 hours of intense coding, AI agent creation, and startup pitches",
    category: "Tech",
    date: "2026-11-02",
    time: "09:00 AM",
    venue: "iHub Innovation Lab, Kilimani",
    city: "Nairobi",
    priceFrom: 1000,
    bannerImage: "/Tech2.jpeg",
    description:
      "Build real-world solutions powered by machine learning, cloud serverless architecture, and Web3. Winners share KES 1,000,000 in seed grants!",
    tags: ["#Hackathon", "#AIBuilders", "#iHub", "#CloudCoding"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-7-1",
        name: "Hacker Ticket",
        price: 1000,
        description: "Includes 48-hour access, meals, high-speed fiber & mentor sessions",
        availableQuantity: 80,
      },
    ],
  },
  {
    id: "evt-8",
    title: "Future of Education & STEM Conference 2026",
    tagline: "Empowering educators, students, and edtech pioneers for next-gen learning",
    category: "Education",
    date: "2026-10-18",
    time: "09:00 AM",
    venue: "Kenyatta International Convention Centre (KICC)",
    city: "Nairobi",
    priceFrom: 2000,
    bannerImage: "/Tech3.jpeg",
    description:
      "A premier national gathering focused on educational innovation, robotics in schools, curriculum transformation, and digital literacy tools for the 21st century.",
    tags: ["#Education", "#EdTech", "#STEM", "#FutureLearning"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-8-1",
        name: "Educator & Student Pass",
        price: 2000,
        description: "Access to keynotes, panel discussions and certificate",
        availableQuantity: 250,
      },
      {
        id: "tier-8-2",
        name: "Institution & Sponsor Pass",
        price: 6000,
        description: "Full access + workshop entry + networking roundtable",
        availableQuantity: 50,
      },
    ],
  },
  {
    id: "evt-9",
    title: "Fintech & Web Architecture Forum 2026",
    tagline: "Payment infrastructure, digital currency & API integrations in Africa",
    category: "Tech",
    date: "2026-12-01",
    time: "10:00 AM",
    venue: "Villa Rosa Kempinski, Westlands",
    city: "Nairobi",
    priceFrom: 5000,
    bannerImage: "/Tech4.jpeg",
    description:
      "Deep-dive discussions on real-time payment rails, micro-services, banking APIs, and financial inclusion tech across Sub-Saharan Africa.",
    tags: ["#Fintech", "#WebArch", "#APIs", "#NairobiTech"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-9-1",
        name: "Forum Delegate Pass",
        price: 5000,
        description: "Access to panel sessions & networking buffet",
        availableQuantity: 120,
      },
    ],
  },
  {
    id: "evt-10",
    title: "Cyber Security & Data Privacy Expo",
    tagline: "Securing cloud workloads, threat intelligence & zero-trust frameworks",
    category: "Tech",
    date: "2026-10-29",
    time: "09:30 AM",
    venue: "Sarit Center Expo Hall, Westlands",
    city: "Nairobi",
    priceFrom: 3500,
    bannerImage: "/Tech5.jpeg",
    description:
      "Exhibitions, threat simulation labs, and expert keynotes on safeguarding enterprise data and defending modern networks against cyber threats.",
    tags: ["#CyberSecurity", "#DataPrivacy", "#InfoSec"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-10-1",
        name: "Expo Pass",
        price: 3500,
        description: "Full day access to live threat labs and vendor floor",
        availableQuantity: 140,
      },
    ],
  },

  /* FOOD & GASTRONOMY (7 IMAGES) */
  {
    id: "evt-11",
    title: "Nairobi Food & Wine Festival 2026",
    tagline: "A culinary journey celebrating East African gastronomy & international vintage wines",
    category: "Food",
    date: "2026-12-05",
    time: "12:00 PM",
    venue: "Village Market Gardens, Gigiri",
    city: "Nairobi",
    priceFrom: 3500,
    bannerImage: "/FOOD1.jpeg",
    description:
      "Indulge in tastings from top Kenyan chefs, artisanal bakeries, craft breweries, and vineyard pop-ups. Features live cooking masterclasses, cocktail competitions, and acoustic jazz sessions.",
    tags: ["#FoodExpo", "#WineTasting", "#NairobiEats", "#CulinaryArt"],
    isPassed: false,
    isFeatured: true,
    ticketTiers: [
      {
        id: "tier-11-1",
        name: "General Tasting Pass",
        price: 3500,
        description: "Includes souvenir wine glass + 5 tasting coupons",
        availableQuantity: 200,
      },
      {
        id: "tier-11-2",
        name: "Connoisseur VIP Pass",
        price: 7500,
        description: "Unlimited reserve wine tasting + Chef's table 4-course seating",
        availableQuantity: 40,
        isPopular: true,
      },
    ],
    vendorOpening: {
      id: "v-3",
      category: "Food & Beverage",
      title: "Artisanal Bakery & Specialty Coffee Vendor Station",
      spotsNeeded: 10,
      spotsRemaining: 3,
      boothFee: 18000,
      boothSize: "3m x 3m Wooden Kiosk",
      perks: ["Running Water Station", "Refrigeration Unit Access", "Social Media Spotlight"],
      deadline: "2026-11-15",
    },
  },
  {
    id: "evt-12",
    title: "Smokey BBQ & Craft Beer Festival",
    tagline: "Slow-roasted meats, local microbreweries, and acoustic country blues",
    category: "Food",
    date: "2026-11-21",
    time: "11:30 AM",
    venue: "Carnivore Grounds, Langata",
    city: "Nairobi",
    priceFrom: 3000,
    bannerImage: "/FOOD2.jpeg",
    description:
      "Pitmasters from across Kenya come together for the ultimate grill showdown. Taste brisket, ribs, roasted plantains, and craft IPA brews.",
    tags: ["#SmokeyBBQ", "#CraftBeer", "#NairobiGrill", "#Foodies"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-12-1",
        name: "BBQ & Beer Pass",
        price: 3000,
        description: "Includes 3 BBQ tasting tokens + 2 craft beer vouchers",
        availableQuantity: 300,
      },
    ],
  },
  {
    id: "evt-13",
    title: "Swahili Seafood & Spice Gala",
    tagline: "Fresh Swahili ocean catch, coconut curries & fragrant spice pop-ups",
    category: "Food",
    date: "2026-12-14",
    time: "13:00 PM",
    venue: "EnglishPoint Marina, Mombasa",
    city: "Mombasa",
    priceFrom: 3200,
    bannerImage: "/FOOD3.jpeg",
    description:
      "Celebrate coastal Swahili cuisine with grilled lobster, biryani, tamarind juice, and traditional coastal musical performances by the marina.",
    tags: ["#SwahiliSeafood", "#CoastalFlavors", "#MombasaEats"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-13-1",
        name: "Marina Feast Ticket",
        price: 3200,
        description: "Includes buffet feast + 1 signature coastal cocktail",
        availableQuantity: 160,
      },
    ],
  },
  {
    id: "evt-14",
    title: "Artisanal Coffee & Roasters Expo",
    tagline: "Specialty Kenyan coffee beans, cupping sessions & barista battles",
    category: "Food",
    date: "2026-10-15",
    time: "09:00 AM",
    venue: "Two Rivers Mall Atrium, Ruaka",
    city: "Nairobi",
    priceFrom: 1500,
    bannerImage: "/FOOD4.jpeg",
    description:
      "Discover world-renowned single-origin Kenyan arabica coffee. Meet local farmers, master roasters, and taste espresso blends.",
    tags: ["#KenyanCoffee", "#BaristaLife", "#CoffeeExpo"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-14-1",
        name: "Cupping Pass",
        price: 1500,
        description: "Unlimited coffee tasting + barista workshop access",
        availableQuantity: 180,
      },
    ],
  },
  {
    id: "evt-15",
    title: "Street Food Truck & Burger Showdown",
    tagline: "Gourmet burgers, loaded fries, tacos & street food innovation",
    category: "Food",
    date: "2026-11-05",
    time: "12:00 PM",
    venue: "Waterfront Mall Courtyard, Karen",
    city: "Nairobi",
    priceFrom: 1800,
    bannerImage: "/FOOD5.jpeg",
    description:
      "Over 20 gourmet food trucks serve custom smash burgers, churros, vegan delights, and craft sodas in an open-air carnival environment.",
    tags: ["#FoodTrucks", "#BurgerShowdown", "#NairobiStreetFood"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-15-1",
        name: "Food Truck Entry",
        price: 1800,
        description: "Includes entry + KES 1,000 food voucher coupon",
        availableQuantity: 250,
      },
    ],
  },
  {
    id: "evt-16",
    title: "Farm-to-Table Organic Harvest Market",
    tagline: "Fresh organic produce, artisanal cheeses, honey & farm lunches",
    category: "Food",
    date: "2026-10-31",
    time: "08:30 AM",
    venue: "Brackenhurst Botanic Gardens, Limuru",
    city: "Limuru",
    priceFrom: 1200,
    bannerImage: "/FOOD6.jpeg",
    description:
      "Spend a weekend morning in Limuru's green hills. Shop organic veggies, farm-fresh cheeses, raw honey, and enjoy a farm-to-table lunch.",
    tags: ["#FarmToTable", "#OrganicMarket", "#LimuruEats"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-16-1",
        name: "Market Visitor Ticket",
        price: 1200,
        description: "Includes entry + complimentary organic tote bag",
        availableQuantity: 300,
      },
    ],
  },
  {
    id: "evt-17",
    title: "Night Food Market & Dessert Carnival",
    tagline: "Midnight street food, artisanal ice creams & glowing food stalls",
    category: "Food",
    date: "2026-12-20",
    time: "19:00 PM",
    venue: "KICC Helipad Deck, Nairobi",
    city: "Nairobi",
    priceFrom: 2200,
    bannerImage: "/FOOD7.jpeg",
    description:
      "Experience Nairobi under the stars with late-night skewers, bubble teas, nitrogen ice creams, and live DJ background sets.",
    tags: ["#NightMarket", "#DessertCarnival", "#NairobiByNight"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-17-1",
        name: "Night Market Pass",
        price: 2200,
        description: "Access to all midnight food kiosks",
        availableQuantity: 220,
      },
    ],
  },

  /* ARTS & CULTURE (5 IMAGES) */
  {
    id: "evt-18",
    title: "Contemporary African Art Biennale 2026",
    tagline: "Exhibiting visionary sculptures, digital art canvas & live canvas performances",
    category: "Arts",
    date: "2026-11-28",
    time: "10:00 AM",
    venue: "National Museum Art Gallery, Museum Hill",
    city: "Nairobi",
    priceFrom: 1800,
    bannerImage: "/ART1.jpeg",
    description:
      "Immerse yourself in groundbreaking visual art from over 40 contemporary artists across Africa. Features live painting installations, NFT digital galleries, and curator talks.",
    tags: ["#FineArt", "#AfricanArt", "#Exhibition", "#Gallery"],
    isPassed: false,
    isFeatured: true,
    ticketTiers: [
      {
        id: "tier-18-1",
        name: "Gallery Admission",
        price: 1800,
        description: "Full day access to main gallery halls and live installations",
        availableQuantity: 180,
      },
      {
        id: "tier-18-2",
        name: "Collector's Gala Pass",
        price: 5000,
        description: "Private preview night, champagne toast & signed catalog",
        availableQuantity: 25,
        isPopular: true,
      },
    ],
    vendorOpening: {
      id: "v-4",
      category: "Art & Craft",
      title: "Handmade Crafts, Sculptures & Fashion Design Booths",
      spotsNeeded: 15,
      spotsRemaining: 6,
      boothFee: 10000,
      boothSize: "2.5m x 2.5m Display Stand",
      perks: ["Spotlights Included", "Security Provided", "Catalog Feature"],
      deadline: "2026-11-10",
    },
  },
  {
    id: "evt-19",
    title: "Digital Canvas & Virtual Reality Gallery",
    tagline: "Step inside interactive 3D digital art and generative projections",
    category: "Arts",
    date: "2026-12-02",
    time: "14:00 PM",
    venue: "Alliance Française, City Centre",
    city: "Nairobi",
    priceFrom: 2200,
    bannerImage: "/ART2.jpeg",
    description:
      "Experience cutting-edge digital art installations, immersive VR headsets, projection mapping onto architectural structures, and digital art auctions.",
    tags: ["#DigitalArt", "#VRGallery", "#GenerativeArt", "#VisualExhibition"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-19-1",
        name: "VR Experience Pass",
        price: 2200,
        description: "Entry to digital gallery + 30 min guided VR session",
        availableQuantity: 100,
      },
    ],
  },
  {
    id: "evt-20",
    title: "African Sculpture & Heritage Woodcraft Expo",
    tagline: "Master sculptors crafting soapstone, ebony & metallic art",
    category: "Arts",
    date: "2026-10-22",
    time: "10:00 AM",
    venue: "Bomas of Kenya, Langata",
    city: "Nairobi",
    priceFrom: 1600,
    bannerImage: "/ART3.jpeg",
    description:
      "Observe live carving masterclasses, traditional beadwork, and bronze sculpting from master artisans representing diverse African cultural heritage.",
    tags: ["#Sculpture", "#Woodcraft", "#AfricanHeritage"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-20-1",
        name: "Exhibition Ticket",
        price: 1600,
        description: "Access to outdoor pavilion & live carving demonstrations",
        availableQuantity: 200,
      },
    ],
  },
  {
    id: "evt-21",
    title: "Contemporary African Photography Exhibition",
    tagline: "Capturing real-world African landscapes, portraits & urban lives",
    category: "Arts",
    date: "2026-11-16",
    time: "11:00 AM",
    venue: "GoDown Arts Centre, Industrial Area",
    city: "Nairobi",
    priceFrom: 1500,
    bannerImage: "/ART4.jpeg",
    description:
      "A curated exhibition featuring award-winning photojournalists and portrait photographers exploring modern African identity, architecture, and wildlife.",
    tags: ["#Photography", "#PhotoExhibition", "#AfricanStories"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-21-1",
        name: "Gallery Pass",
        price: 1500,
        description: "Full exhibition access + artist talk session",
        availableQuantity: 150,
      },
    ],
  },
  {
    id: "evt-22",
    title: "Live Canvas & Graffiti Art Festival",
    tagline: "Street muralists transforming blank walls into vibrant urban art",
    category: "Arts",
    date: "2026-12-10",
    time: "12:00 PM",
    venue: "Shankardass House Alley, CBD",
    city: "Nairobi",
    priceFrom: 1200,
    bannerImage: "/ART5.jpeg",
    description:
      "Watch urban graffiti painters, muralists, and street artists collaborate live on large-scale public murals accompanied by DJ sets.",
    tags: ["#GraffitiArt", "#LiveCanvas", "#UrbanMurals"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-22-1",
        name: "Festival Pass",
        price: 1200,
        description: "Access to mural alleys & live spray paint workshops",
        availableQuantity: 220,
      },
    ],
  },

  /* FASHION & STYLE (6 IMAGES) */
  {
    id: "evt-23",
    title: "Afro-Chic Runway & Style Expo 2026",
    tagline: "Redefining East African luxury, streetwear, and avant-garde couture",
    category: "Fashion",
    date: "2026-11-20",
    time: "17:00 PM",
    venue: "Radisson Blu Ballroom, Upper Hill",
    city: "Nairobi",
    priceFrom: 5000,
    bannerImage: "/Fashion1.jpeg",
    description:
      "A spectacular high-fashion runway showcase highlighting top African designers, sustainable textiles, bespoke menswear, and luxury accessory pop-ups.",
    tags: ["#NairobiFashion", "#AfroChic", "#Runway2026", "#StyleGala"],
    isPassed: false,
    isFeatured: true,
    ticketTiers: [
      {
        id: "tier-23-1",
        name: "Standard Runway Seat",
        price: 5000,
        description: "Tiered seating with view of main cat walk",
        availableQuantity: 120,
      },
      {
        id: "tier-23-2",
        name: "Front Row VIP & Gift Bag",
        price: 15000,
        description: "Front row seating + designer gift bag & cocktail lounge entry",
        availableQuantity: 30,
        isPopular: true,
      },
    ],
    vendorOpening: {
      id: "v-5",
      category: "Merch & Retail",
      title: "Designer Boutique & Fashion Accessory Display Booths",
      spotsNeeded: 10,
      spotsRemaining: 5,
      boothFee: 20000,
      boothSize: "3m x 3m Luxury Pop-Up Booth",
      perks: ["Custom Fitting Room Space", "Mannequins Included", "VIP Fashion Buyer Access"],
      deadline: "2026-11-05",
    },
  },
  {
    id: "evt-24",
    title: "Streetwear & Urban Culture Carnival",
    tagline: "Sneakerhead drops, graffiti art battles & underground hip-hop beats",
    category: "Fashion",
    date: "2026-12-12",
    time: "13:00 PM",
    venue: "Waterfront Mall Courtyard, Karen",
    city: "Nairobi",
    priceFrom: 2000,
    bannerImage: "/Fashion2.jpeg",
    description:
      "Celebrating urban youth culture, custom sneaker customization stations, vintage thrift pop-ups, skater competitions, and live cyphers.",
    tags: ["#Streetwear", "#UrbanCulture", "#SneakerDrop", "#NairobiStyle"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-24-1",
        name: "Carnival Access Pass",
        price: 2000,
        description: "Access to main grounds & skate park",
        availableQuantity: 200,
      },
      {
        id: "tier-24-2",
        name: "Exclusive Drop Pass",
        price: 4500,
        description: "Early access to limited edition sneaker drops & free merch tee",
        availableQuantity: 50,
      },
    ],
  },
  {
    id: "evt-25",
    title: "Haute Couture & Luxury Tailoring Gala",
    tagline: "Bespoke evening gowns, tailored suits & velvet red carpet glam",
    category: "Fashion",
    date: "2026-10-30",
    time: "18:00 PM",
    venue: "Sankara Rooftop Lounge, Westlands",
    city: "Nairobi",
    priceFrom: 6500,
    bannerImage: "/Fashion3.jpeg",
    description:
      "An opulent evening showcasing hand-stitched silk gowns, custom tuxedo tailoring, and luxury gemstone jewelry worn by top fashion models.",
    tags: ["#HauteCouture", "#LuxuryFashion", "#RedCarpet"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-25-1",
        name: "Gala Dinner Ticket",
        price: 6500,
        description: "Includes 3-course dinner + front row runway view",
        availableQuantity: 80,
      },
    ],
  },
  {
    id: "evt-26",
    title: "Sustainable Textile & Eco-Fashion Expo",
    tagline: "Organic cottons, recycled denim & eco-friendly fashion design",
    category: "Fashion",
    date: "2026-11-25",
    time: "10:00 AM",
    venue: "Sarolea Eco Pavilion, Gigiri",
    city: "Nairobi",
    priceFrom: 2500,
    bannerImage: "/Fashion4.jpeg",
    description:
      "Discover the future of eco-conscious fashion. Workshops on zero-waste pattern drafting, botanical fabric dyes, and ethical manufacturing.",
    tags: ["#EcoFashion", "#SustainableStyle", "#GreenTextiles"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-26-1",
        name: "Expo Pass",
        price: 2500,
        description: "Access to eco-exhibitors & design panels",
        availableQuantity: 130,
      },
    ],
  },
  {
    id: "evt-27",
    title: "Vintage Thrift & Y2K Style Market",
    tagline: "Curated vintage denim, retro leather jackets & Y2K accessories",
    category: "Fashion",
    date: "2026-10-12",
    time: "11:00 AM",
    venue: "Nairobi Arboretum Gardens, Kileleshwa",
    city: "Nairobi",
    priceFrom: 1000,
    bannerImage: "/Fashion5.jpeg",
    description:
      "Shop over 40 vintage fashion curators offering rare 90s windbreakers, leather boots, retro sunglasses, and upcycled denim clothing.",
    tags: ["#VintageThrift", "#Y2KFashion", "#ThriftNairobi"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-27-1",
        name: "Market Ticket",
        price: 1000,
        description: "Includes early entry & thrift tote bag",
        availableQuantity: 300,
      },
    ],
  },
  {
    id: "evt-28",
    title: "African Jewelry & Accessories Showcase",
    tagline: "Handcrafted brass necklaces, Maasai beadwork & leather bags",
    category: "Fashion",
    date: "2026-12-08",
    time: "10:30 AM",
    venue: "Westgate Shopping Mall Atrium",
    city: "Nairobi",
    priceFrom: 1500,
    bannerImage: "/Fashion6.jpeg",
    description:
      "Exquisite artisanal jewelry from East African metalworkers and leather craftsmen. Perfect for holiday fashion shopping and styling.",
    tags: ["#AfricanJewelry", "#MaasaiBeadwork", "#Accessories"],
    isPassed: false,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-28-1",
        name: "Showcase Ticket",
        price: 1500,
        description: "Access to main exhibition hall",
        availableQuantity: 180,
      },
    ],
  },

  /* HISTORICAL / PASSED EVENTS (GREYED OUT EXAMPLES) */
  {
    id: "evt-29",
    title: "Summer Grill & Beer Expo (Summer Edition)",
    tagline: "The premier summer food fair & grill master showdown",
    category: "Food",
    date: "2026-07-02",
    time: "11:00 AM",
    venue: "Sarit Expo Centre, Westlands",
    city: "Nairobi",
    priceFrom: 2000,
    bannerImage: "/FOOD2.jpeg",
    description:
      "This event has concluded. Hundreds of foodies gathered for smoked BBQ competitions, craft beer tastings, and celebrity chef demos.",
    tags: ["#PastEvent", "#FoodExpo", "#SavorNairobi"],
    isPassed: true,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-29-1",
        name: "General Admission (Ended)",
        price: 2000,
        description: "Event has concluded",
        availableQuantity: 0,
      },
    ],
  },
  {
    id: "evt-30",
    title: "Coast Film & Cinema Festival 2026",
    tagline: "Celebrating indie African cinema, documentary shorts & VR experiences",
    category: "Arts",
    date: "2026-08-15",
    time: "14:00 PM",
    venue: "Fort Jesus Heritage Amphitheatre, Mombasa",
    city: "Mombasa",
    priceFrom: 3000,
    bannerImage: "/ART3.jpeg",
    description:
      "This event has concluded. A 3-day beachside film screening showcasing award-winning filmmakers from across the continent.",
    tags: ["#FilmFestival", "#AfricanCinema", "#MombasaEvents"],
    isPassed: true,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-30-1",
        name: "Festival Pass (Ended)",
        price: 3000,
        description: "Event has concluded",
        availableQuantity: 0,
      },
    ],
  },
  {
    id: "evt-31",
    title: "Vantage High Fashion Autumn Preview",
    tagline: "An exclusive autumn preview of African luxury couture",
    category: "Fashion",
    date: "2026-06-10",
    time: "19:00 PM",
    venue: "Villa Rosa Kempinski, Westlands",
    city: "Nairobi",
    priceFrom: 6000,
    bannerImage: "/Fashion4.jpeg",
    description:
      "This event has concluded. High-fashion gala displaying autumn/winter collections from East African couture houses.",
    tags: ["#PastFashion", "#KempinskiGala", "#HauteCouture"],
    isPassed: true,
    isFeatured: false,
    ticketTiers: [
      {
        id: "tier-31-1",
        name: "Gala Pass (Ended)",
        price: 6000,
        description: "Event has concluded",
        availableQuantity: 0,
      },
    ],
  },
];
